from TaskScheduler.Algorithms.RoundRobin import RoundRobin
from TaskScheduler.Algorithms.Random import Random
from TaskScheduler.Algorithms.ShortestProcessingTime import ShortestProcessingTime
from TaskScheduler.Algorithms.EarliestDueTime import EarliestDueTime
from TaskScheduler.Algorithms.CriticalRatio import CriticalRatio